### ISSUE TITLE
Screenshot Tool caused system and desktop font to change to Redacted Font (squiggles)

### ISSUE THREAD

**Issue by ch0chi** [elementary/screenshot-tool#60] opened 2017-10-11 17:13 UTC
Very weird issue, was using the screenshot-tool to snap a pic to send to a client. I selected the "select area to grab" option, clicked "screenshot", moved my mouse right, and shortly after my desktop and system fonts changed to Redacted Font (squiggles). I managed to fix the issue by changing the font back using elementary-tweak-tools, resizing the desktop using tweak tools, changing the sizing back to it's original value, and restarting.

Any idea on what caused this? Here's a [screenshot](https://imgur.com/a/nULk3) of the issue.

**Comment by ch0chi** [comment] 2017-10-18 14:44
I have fixed the issue, but have now noticed system/desktop fonts change to Redacted whenever a screenshot is taken. Here is a [gif](https://imgur.com/a/xlJMV) of the issue happening.

**Comment by fabiozaramella** [comment] 2017-11-05 20:55
This is the intended behaviour when "Conceal text" option is active, which is the case as shown in the gif you provided. I'm marking this as Invalid.

**Closed by fabiozaramella** 2017-11-05 20:55 UTC
Labels: Status: Invalid
