### ISSUE TITLE
Screenshot area is shown with a grey layer on top

### ISSUE THREAD

**Issue by Gabriel-p** [elementary/screenshot-tool#37] opened 2017-06-03 14:52 UTC
5 out of 10 times when using the `screenshot-tool -r` shortcut to select only an area of the screen, the screenshot is stored with a transparent grey layer on top.

**Comment by artemanufrij** [comment] 2017-08-05 11:08
I can't reproduce it. All > 20 screenshots are as expected...

**Comment by artemanufrij** [comment] 2018-03-21 23:26
I'm going to close it because it can't be reproduced

**Closed by artemanufrij** 2018-03-21 23:26 UTC
Labels: Status: Incomplete

**Comment by Gabriel-p** [comment] 2018-03-22 01:10
Reproduced on the first try.

![captura realizada el 2018-03-21 22 10 21](https://user-images.githubusercontent.com/6054951/37745637-aabf36b2-2d54-11e8-8abc-23e6da2e1995.png)

**Comment by artemanufrij** [comment] 2018-03-22 09:08
weird... It was never happened on my system

![bildschirmfoto von 2018-03-22 10 05 21](https://user-images.githubusercontent.com/16517095/37761043-d2b9373a-2db8-11e8-8126-c2d31e8336a0.png)

**Comment by artemanufrij** [comment] 2018-03-22 09:09
PS: tested on three different systems

**Comment by Gabriel-p** [comment] 2018-03-22 12:19
Try using the keyboard shortcut Shift+PrtScrn which is what I use. These are my specs BTW:

> AMD A8-3870 APU with Radeon(tm) HD Graphics
> NVIDIA Corporation G96 [GeForce 9500 GT] (rev a1)

**Comment by danrabbit** [comment] 2018-03-23 18:41
Ah, if you're using a keyboard shortcut, then the screenshot is being taken by Gala. Please report here: https://github.com/elementary/gala

**Comment by Gabriel-p** [comment] 2018-03-23 18:47
Done @danrabbit: https://github.com/elementary/gala/issues/211
